### PR TITLE
config: add support for showing %H%M%S along with build date

### PR DESCRIPTION
**Pull request by rahul9999xda**
Signed-off-by: rahul9999xda <rahul9999xda@gmail.com>

### CODE REVIEW

**Review by NurKeinNeid — COMMENTED** [review]
Lets do this conditonally like in Q.  Only for CI builds for example.

**Comment by rahul9999xda** [comment]
Can we have an option for non CI builds?

**Comment by NurKeinNeid** [comment]
You want it in official builds?

**Comment by rahul9999xda** [comment]
> You want it in official builds?

Yes

**Comment by NurKeinNeid** [comment]
https://github.com/DerpFest-11/vendor_derp/commit/f9161170629a36c4b55ff1b8b792267d76459bf6

The maximum what I can offer.

**Comment by rahul9999xda** [comment]
> [f916117](https://github.com/DerpFest-11/vendor_derp/commit/f9161170629a36c4b55ff1b8b792267d76459bf6)
> 
> The maximum what I can offer.

Thanks.. should be enough ;)

**Pull request closed without merging**
